create database mobile;
use mobile;

select * from sales;

-- 1. What is the total revenue generated from all mobile sales?

select sum(`units sold`*`price per unit`) as total_revenue
from sales; 

-- 2. Which mobile brand sold the most units?

select brand, sum(`units sold`) as units
from sales
group by brand 
order by units desc;

-- 3. Top 5 Cities with Highest Sales Revenue

select * from sales;

select city, sum(`units sold`*`price per unit`) as total_revenue
from sales
group by city 
order by total_revenue
limit 5;

-- 4. Best Selling Mobile Model

select * from sales;

select `mobile model`, sum(`units sold`) as best_mobile
from sales
group by `mobile model`
order by best_mobile; 

-- 5. Average Customer Rating by Brand

select brand, avg(`customer ratings`) as avg_ratings
from sales
group by brand
order by avg_ratings; 

-- 6. Revenue Generated by Payment Method

select `payment method`,sum(`units sold`*`price per unit`) as total_revenue
from sales
group by `payment method`
order by total_revenue desc;

-- 7. Total Sales per Year

select year, sum(`units sold`*`price per unit`) as total_sales
from sales
group by year 
order by year;

-- 8. Average Price per Unit by Brand

select brand, avg(`price per unit`) as avg_price
from sales
group by brand
order by avg_price;

-- 9. Top 10 Customers Who Purchased the Most Unit

select * from sales;

select `customer name`,sum(`units sold`) as total_unit
from sales
group by `customer name`
order by total_unit desc
limit 10;   

-- 10. Daily Sales Revenue

select date,sum(`units sold` * `price per unit`) as revenue
from sales
group by date
order by date;

-- 11. City-wise Average Customer Age

select city, avg(`customer age`) as avg_age
from sales
group by city;

-- 12. Highest Revenue Generating Brand

select brand, sum(`units sold`*`price per unit`) as highest_revenue
from sales
group by brand
order by highest_revenue desc
limit 1;

-- 13. Sales Distribution by Day of Week

select * from sales;

SET SQL_SAFE_UPDATES = 0;

UPDATE sales
SET `day name` = 'Monday'
WHERE `day name` IN ('Mon','monday','mon',' MON');

UPDATE sales
SET `day name` = 'Tuesday'
WHERE `day name` IN ('Tue','tue','TUE');

UPDATE sales
SET `day name` = 'Wednesday'
WHERE `day name` IN ('Wed','wed');

UPDATE sales
SET `day name` = 'Thursday'
WHERE `day name` IN ('Thu','thu');

UPDATE sales
SET `day name` = 'Friday'
WHERE `day name` IN ('Fri','fri');

UPDATE sales
SET `day name` = 'Saturday'
WHERE `day name` IN ('Sat','sat');

UPDATE sales
SET `day name` = 'Sunday'
WHERE `day name` IN ('Sun','sun');

SELECT `day name`, SUM(`units sold`) AS units
FROM sales
GROUP BY `day name`
ORDER BY units DESC;

-- 14. Top 5 Most Expensive Mobile Models

select `mobile model`,max(`price per unit`) as expensive
from sales
group by `mobile model` 
order by expensive desc
limit 5;

-- 15. Revenue by City and Brand

select city, brand, sum(`units sold`*`price per unit`) as revenue
from sales
group by city,brand
order by revenue desc;

-- 16. Number of Transactions per Payment Method. 

select `payment method`, count(`transaction id`) as transactions
from sales
group by `payment method`;

-- 17. Average Units Sold per Transaction

select avg(`units sold`) as avg_units
from sales;

-- 18. Cities with Highest Average Customer Rating

select city, avg(`customer ratings`) as avg_ratings
from sales
group by city
order by avg_ratings desc;

-- 19. Monthly Revenue Trend 

select * from sales;

SELECT 
MONTHNAME(STR_TO_DATE(date,'%Y-%m-%d')) AS month_name,
SUM(`units sold` * `price per unit`) AS revenue
FROM sales
GROUP BY month_name
ORDER BY revenue DESC;

-- 20. Customers Who Purchased More Than 5 Units in Total

select `customer name`, sum(`units sold`) as total_units
from sales
group by `customer name`
having sum(`units sold`) > 5
order by total_units desc; 
 


